name: Acceptance Stage

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  acceptance-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check if Docker Images have Updated Recently
        id: check-images
        run: |
          IMAGES=("${{ secrets.DOCKER_USERNAME }}/fe" "${{ secrets.DOCKER_USERNAME }}/task-manager" "${{ secrets.DOCKER_USERNAME }}/title-generator")

          # Obtener el tiempo actual en formato Unix (epoch)
          CURRENT_TIME=$(date +%s)
          IMAGES_UPDATED=false

          for IMAGE in "${IMAGES[@]}"; do
            # Obtener la marca de tiempo de la última actualización de la imagen
            LAST_UPDATED=$(curl -s "https://hub.docker.com/v2/repositories/$IMAGE/tags" | jq -r '.results[0].last_updated')
            LAST_UPDATED_EPOCH=$(date -d "$LAST_UPDATED" +%s)

            # Calcular la diferencia en minutos
            DIFF_MINUTES=$(( (CURRENT_TIME - LAST_UPDATED_EPOCH) / 60 ))

            echo "$IMAGE was last updated $DIFF_MINUTES minutes ago."

            # Verificar si la imagen se actualizó en los últimos 5 minutos
            if [ "$DIFF_MINUTES" -le 5 ]; then
              IMAGES_UPDATED=true
              echo "$IMAGE was updated within the last 5 minutes."
              break  # Salir del ciclo si se encuentra una imagen actualizada
            fi
          done

          echo "IMAGES_UPDATED=$IMAGES_UPDATED" >> $GITHUB_ENV

      - name: Log No Update Found
        if: env.IMAGES_UPDATED == 'false'
        run: echo "Workflow checked for updates but found no recent image updates."

      - name: Stop Workflow if No Images Have Updated Recently
        if: env.IMAGES_UPDATED == 'false'
        run: exit 0

      - name: Trigger Generic System Release
        if: env.IMAGES_UPDATED == 'true'
        uses: actions/github-script@v4
        id: trigger-release
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const workflow = 'Generic System Release Stage';
            const response = await github.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
            });

            const workflow_id = response.data.workflows.find(w => w.name === workflow)?.id;

            if (!workflow_id) {
              throw new Error(`No workflow found with name: ${workflow}`);
            }

            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflow_id,
              ref: context.ref,
              inputs: {
                environment: 'acceptance'
              }
            });

      - name: Checkout repository
        if: env.IMAGES_UPDATED == 'true'
        uses: actions/checkout@v4

      - name: Install dependencies
        if: env.IMAGES_UPDATED == 'true'
        run: npm install

      - name: Run Smoke Tests
        if: env.IMAGES_UPDATED == 'true'
        run: echo "Running smoke tests..." && npm run test:smoke

      - name: Wait for Generic System Release to finish
        if: env.IMAGES_UPDATED == 'true'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const workflow = 'Generic System Release Stage';
            const response = await github.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
            });

            const workflow_id = response.data.workflows.find(w => w.name === workflow)?.id;

            if (!workflow_id) {
              throw new Error(`No workflow found with name: ${workflow}`);
            }

            let completed = false;
            let attempts = 0;
            const max_attempts = 60;

            while (!completed && attempts < max_attempts) {
              const run = await github.actions.listWorkflowRuns({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: workflow_id,
                status: 'in_progress',
              });

              if (run.data.total_count === 0) {
                completed = true;
              } else {
                console.log('Generic System Release Stage still in progress, waiting...');
                await new Promise(r => setTimeout(r, 10000));
              }
              attempts++;
            }

            if (!completed) {
              throw new Error('Timeout: Generic System Release Stage did not complete in time');
            }

      - name: Run Acceptance Tests
        if: env.IMAGES_UPDATED == 'true'
        run: echo "Running acceptance tests..." && npm run test:acceptance

      - name: Run Curl Tests
        if: env.IMAGES_UPDATED == 'true'
        run: |
          echo "Checking if Task Manager is up..."
          curl -f http://${{ secrets.ACCEPTANCE_VM_IP }}:3001/health || exit 1
          echo "Checking if Title Generator is up..."
          curl -f http://${{ secrets.ACCEPTANCE_VM_IP }}:3002/health || exit 1
